# Runs with hot code reload (for development purposes)

FROM node:13-alpine
ENV TERM xterm-256color

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY src ./src
ENTRYPOINT ["npm", "run", "dev"]