name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Get files names from the last commit, extract top-level folder names
      run: |
        git log -1
        git log --oneline -1 --name-only
        echo ::set-env name=FOLDERS_CHANGED::$(git log --oneline -1 --name-only | tail -n +2 | cut -d'/' -f1)
      
#     - name: SegmentStream
#       #if: ${{ contains (env.FOLDERS_CHANGED, "SegmentStream") }}
#       run: |
#         echo ${{ env.FOLDERS_CHANGED }}
#         cd SegmentStream/redis-caching-proxy
#         make test
